import * as XLSX from 'xlsx';
import { lookupOriginal } from './ssisLineage';

/* ─────────────────────────────────────────────────────────
   Source-to-Target mapping workbook (Kimball star schema).
   Eight sheets matching the team's standard template:
     README · Source_To_Target_Map · Source_Join_Rules ·
     Column_Mapping · Fact_Dim_Lookups · ETL_Rules · DQ_Rules ·
     Visual_Flow.
   buildWorkbook(results) is a PURE function (XLSX only) so it can be
   unit-tested in Node; exportExcel / exportJSON add the browser
   download via a dynamic import of file-saver.
   results: [{ fileName, content, result }]
───────────────────────────────────────────────────────── */

const NA = 'N/A';
const UNKNOWN_KEY = '-1';

/* ── small helpers ─────────────────────────────────────── */
const clean = (v) => (v === undefined || v === null || v === '' ? '' : String(v));

function stripPrefix(name = '') {
  return String(name).replace(/^(DIM|FACT)_?/i, '').replace(/^_+/, '');
}

/* DIM_CUSTOMER_SEGMENT -> "Customer Segment" */
function friendly(name = '') {
  return stripPrefix(name)
    .split(/[_\s]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ');
}

/* surrogate-key column name for a dimension */
function surrogateName(dim) {
  if (dim?.surrogate_key) return dim.surrogate_key;
  return friendly(dim?.name).replace(/\s+/g, '') + '_Key';
}

/* base tables that feed a fact/dimension (real names only) */
function srcTablesOf(t, fallback) {
  const list =
    Array.isArray(t?.source_tables) && t.source_tables.length
      ? t.source_tables
      : t?.source_table
      ? [t.source_table]
      : fallback || [];
  return list.filter(Boolean);
}

/* "SourceA + SourceB -> Target" */
function mappingSummary(target, srcList) {
  const left = srcList.length ? srcList.join(' + ') : '(source unconfirmed)';
  return `${left} -> ${target}`;
}

/* fallback SQL data type when the model didn't supply one */
function inferType(name = '') {
  const n = String(name).toLowerCase();
  if (/(_key$|key$|_id$|^id$)/.test(n)) return 'INT';
  if (/(date|_dt$|timestamp)/.test(n)) return 'DATE';
  if (/(amount|balance|amt|_bal|value|total)/.test(n)) return 'DECIMAL(18,2)';
  if (/(count|number|num$|qty|quantity)/.test(n)) return 'INT';
  if (/(flag|status|_ind$|_yn$)/.test(n)) return 'VARCHAR(20)';
  if (/(name|desc|description|address)/.test(n)) return 'VARCHAR(100)';
  return 'VARCHAR(50)';
}

/* dimension column mappings, with a fallback when none were produced */
function dimMappings(dim) {
  if (dim?.column_mappings?.length) return dim.column_mappings;
  const out = [];
  if (dim?.business_key) {
    out.push({
      target_column: dim.business_key,
      source_column: dim.business_key,
      transformation: `Direct copy from ${dim.business_key}`,
      key_type: 'Business Key',
      nullable: 'No',
      data_quality: 'NOT NULL · UNIQUE',
    });
  }
  (dim?.attributes ?? []).forEach((a) =>
    out.push({
      target_column: a,
      source_column: a,
      transformation: `Direct copy from ${a}`,
      key_type: 'Attribute',
      nullable: 'Yes',
      data_quality: 'Check for nulls',
    }),
  );
  return out;
}

/* ── README (sheet 1) ──────────────────────────────────── */
function readmeRows(results) {
  const rows = [['Item', 'Description']];
  rows.push([
    'Workbook Purpose',
    'Maps source tables and columns to a Kimball star schema (dimensions + facts) for the Cognos to Cloudera migration.',
  ]);
  const reports = results.map((r) => r.result?.report_name || r.fileName).filter(Boolean);
  if (reports.length) rows.push(['Reports', reports.join(' · ')]);
  results.forEach((r) => {
    const v = r.result || {};
    if (v.grain) rows.push([`Grain — ${v.report_name || r.fileName}`, v.grain]);
  });
  rows.push(['Recommended Load Order', '1) Reference / lookup tables, 2) Dimensions, 3) Facts']);
  rows.push([
    'Dimension Principle',
    'Each dimension has an INT surrogate key (ETL-generated) plus the business / natural key from the source.',
  ]);
  rows.push([
    'Fact Principle',
    'Facts store measures at the stated grain and reference dimensions by surrogate key.',
  ]);
  rows.push([
    'Unknown Member',
    'Every dimension has an Unknown member with surrogate key = -1; fact lookups that miss default to -1.',
  ]);
  rows.push([
    'SCD Handling',
    "Type 1 = overwrite in place. Type 2 = keep history with effective / end dates and an IsCurrent flag.",
  ]);
  rows.push([
    'Sheets',
    'Source_To_Target_Map, Source_Join_Rules, Column_Mapping, Fact_Dim_Lookups, ETL_Rules, DQ_Rules, Visual_Flow',
  ]);
  rows.push(['Generated By', 'AI Dimensional Modeler']);
  return rows;
}

function readmeLineageRow(lineage) {
  return [
    'SSIS Lineage',
    `Original source-system tables resolved from ${lineage.packages.size} SSIS package(s) / load script(s) — see the Source_Lineage sheet and the "Original Source Table (RAW)" columns.`,
  ];
}

/* ── ETL_Rules (sheet 6) — generic + load guidance ─────── */
function etlRows() {
  const H = ['Rule ID', 'Area', 'Rule Description', 'Applies To', 'Action'];
  const r = [
    ['Load Order', 'Load reference / lookup tables, then dimensions, then facts', 'All tables', 'Sequence loads'],
    ['Dimension Load', 'Check if the business key already exists in the dimension', 'All dimensions', 'Insert if not exists'],
    ['Surrogate Keys', 'Generate the surrogate key via identity / sequence', 'All dimensions', 'Generate key'],
    ['Unknown Member', 'Seed each dimension with an Unknown member (surrogate key = -1)', 'All dimensions', 'Insert default row'],
    ['SCD Type 1', 'Overwrite changed attributes in place', 'Type 1 dimensions', 'Update record'],
    ['SCD Type 2', 'Expire the current row and insert a new version with effective / end dates', 'Type 2 dimensions', 'Version record'],
    ['Fact Lookup', 'Resolve each foreign key by business-key lookup; use -1 when not found', 'All facts', 'Lookup surrogate key'],
    ['Audit', 'Stamp load timestamps (dw_created_date / dw_updated_date)', 'All tables', 'Set audit columns'],
  ];
  return [H, ...r.map((row, i) => [`ETL_${String(i + 1).padStart(3, '0')}`, ...row])];
}

/* Values in a Source Table cell that are placeholders, not real tables. */
const NOT_A_TABLE = /^$|^n\/?a$|etl generated|etl system|needs confirmation|recommended|⚠/i;

/* ─────────────────────────────────────────────────────────
   PURE: build the workbook from analysis results.
   `lineage` (optional) is the SSIS lineage store from ssisLineage.js —
   when present, mart-layer (Cognos) source tables are resolved to the
   ORIGINAL source-system tables and shown alongside them.
───────────────────────────────────────────────────────── */
export function buildWorkbook(results, lineage) {
  const list = Array.isArray(results) ? results.filter((r) => r?.result) : [];
  const hasLineage = (lineage?.entries?.length ?? 0) > 0;

  /* mart table → original source tables (or a warning when unmapped) */
  const origOf = (table) => {
    const t = String(table ?? '').trim();
    if (!hasLineage || NOT_A_TABLE.test(t)) return '';
    const hit = lookupOriginal(lineage, t);
    return hit ? hit.sources.join(', ') : '⚠ No SSIS lineage found';
  };
  /* multi-table cell ("A, B") → union of original sources */
  const origOfList = (cell) => {
    const tables = String(cell ?? '').split(',').map((s) => s.trim()).filter((s) => s && !NOT_A_TABLE.test(s));
    if (!hasLineage || !tables.length) return '';
    const out = [];
    let unmapped = 0;
    tables.forEach((t) => {
      const hit = lookupOriginal(lineage, t);
      if (!hit) { unmapped++; return; }
      hit.sources.forEach((s) => { if (!out.includes(s)) out.push(s); });
    });
    let txt = out.join(', ');
    if (unmapped) txt += `${txt ? ' ' : ''}(⚠ ${unmapped} table(s) without SSIS lineage)`;
    return txt;
  };

  const mapHeader = ['Mapping ID', 'Target Type', 'Target Table', 'Source Tables', 'Join Logic', 'Load Dependency', 'Mapping Summary'];
  const joinHeader = ['Mapping ID', 'Target Table', 'Primary Source Table', 'Secondary Source Table', 'Join Type', 'Join Condition', 'Filter Condition', 'Purpose'];
  const colHeader = ['Mapping ID', 'Target Table', 'Target Column', 'Target Data Type', 'Source Table', 'Source Column', 'Transformation / Rule', 'Lookup Dimension', 'Nullable', 'Default Value', 'Key/Measure Type', 'SCD/Aggregation'];
  const lookupHeader = ['Fact Column', 'Source Business Key', 'Dimension Table', 'Dimension Business Key', 'Dimension Surrogate Key', 'Lookup Rule', 'Default If Not Found', 'Comments'];
  const dqHeader = ['DQ Rule ID', 'Table', 'Column', 'Rule', 'Severity', 'Action'];
  const flowHeader = ['Area', 'Flow'];

  const mapRows = [mapHeader];
  const joinRows = [joinHeader];
  const colRows = [colHeader];
  const lookupRows = [lookupHeader];
  const dqRows = [dqHeader];
  const flowRows = [flowHeader];

  let mapSeq = 0;
  let dqSeq = 0;
  const nextMap = () => `MAP_${String(++mapSeq).padStart(3, '0')}`;
  const nextDq = () => `DQ_${String(++dqSeq).padStart(3, '0')}`;

  list.forEach((r) => {
    const v = r.result || {};
    const dims = v.dimensions ?? [];
    const facts = v.facts ?? [];
    const dimByName = {};
    dims.forEach((d) => (dimByName[d.name] = d));
    const firstFact = facts[0]?.name || 'the fact';

    /* ---- DIMENSIONS (load first) ---- */
    dims.forEach((dim) => {
      const mapId = nextMap();
      const name = dim.name;
      const srcList = srcTablesOf(dim, []);
      const primarySrc = srcList[0] || dim.source_table || NA;
      const joins = dim.join_rules ?? [];

      // Source_To_Target_Map
      const joinLogic = joins.length
        ? joins.map((j) => j.purpose).filter(Boolean).join('; ')
        : srcList.length > 1
        ? `Joins ${srcList.join(', ')}`
        : 'Single source table';
      mapRows.push([
        mapId, 'Dimension', name, srcList.join(', ') || (dim.source_table ?? ''),
        joinLogic || 'Single source table', `Load before ${firstFact}`, mappingSummary(name, srcList),
      ]);

      // Source_Join_Rules
      joins.forEach((j) =>
        joinRows.push([
          mapId, name, clean(j.primary_source_table) || NA, clean(j.secondary_source_table) || NA,
          clean(j.join_type) || 'JOIN', clean(j.join_condition) || 'needs confirmation',
          clean(j.filter_condition) || NA, clean(j.purpose),
        ]),
      );

      // Column_Mapping — surrogate key row
      colRows.push([
        mapId, name, surrogateName(dim), 'INT', 'ETL Generated', NA, 'Generate surrogate key',
        NA, 'No', NA, 'Surrogate Key', NA,
      ]);
      // Column_Mapping — business key + attributes
      dimMappings(dim).forEach((cm) => {
        const isBK = (cm.key_type || '').toLowerCase().includes('business') || cm.target_column === dim.business_key;
        const keyType = cm.key_type || (isBK ? 'Business Key' : 'Attribute');
        colRows.push([
          mapId, name, clean(cm.target_column),
          clean(cm.target_data_type) || inferType(cm.target_column),
          clean(cm.source_table) || primarySrc, clean(cm.source_column),
          clean(cm.transformation), clean(cm.lookup_dimension) || NA,
          clean(cm.nullable) || (isBK ? 'No' : 'Yes'),
          clean(cm.default_value) || NA, keyType, dim.scd_type || 'Type 1',
        ]);
        // DQ rule for the business key
        if (isBK) {
          dqRows.push([nextDq(), name, clean(cm.target_column), 'Must not be null and must be unique', 'High', 'Reject record']);
        } else if ((cm.default_value || '').toLowerCase() === 'unknown') {
          dqRows.push([nextDq(), name, clean(cm.target_column), 'If null, set to Unknown', 'Medium', 'Default value']);
        }
      });
      // Column_Mapping — audit columns
      colRows.push([mapId, name, 'dw_created_date', 'DATE', 'ETL System', NA, 'Load timestamp (insert)', NA, 'No', NA, 'Audit', NA]);
      colRows.push([mapId, name, 'dw_updated_date', 'DATE', 'ETL System', NA, 'Load timestamp (update)', NA, 'No', NA, 'Audit', NA]);

      // Visual_Flow
      flowRows.push([`${friendly(name)} Dimension`, mappingSummary(name, srcList)]);
    });

    /* ---- FACTS (load after dimensions) ---- */
    facts.forEach((fact) => {
      const mapId = nextMap();
      const name = fact.name;
      const srcList = srcTablesOf(fact, v.source_tables ?? []);
      const primarySrc = srcList[0] || NA;
      const joins = fact.join_rules ?? [];

      // Source_To_Target_Map
      const joinLogic = joins.length
        ? joins.map((j) => j.purpose).filter(Boolean).join('; ')
        : srcList.length > 1
        ? `Joins ${srcList.join(', ')}`
        : 'Single source table';
      mapRows.push([
        mapId, 'Fact', name, srcList.join(', '),
        joinLogic || 'Single source table', 'Load after all dimensions', mappingSummary(name, srcList),
      ]);

      // Source_Join_Rules
      joins.forEach((j) =>
        joinRows.push([
          mapId, name, clean(j.primary_source_table) || NA, clean(j.secondary_source_table) || NA,
          clean(j.join_type) || 'JOIN', clean(j.join_condition) || 'needs confirmation',
          clean(j.filter_condition) || NA, clean(j.purpose),
        ]),
      );

      // Column_Mapping — foreign keys + Fact_Dim_Lookups
      (fact.foreign_keys ?? []).forEach((fk) => {
        const dim = dimByName[fk];
        const fkCol = surrogateName(dim || { name: fk });
        const bk = dim?.business_key || 'needs confirmation';
        // Column_Mapping: a fact FK's immediate source is the dimension's surrogate key,
        // resolved by the dimension business key (never a guessed fact source table).
        colRows.push([
          mapId, name, fkCol, 'INT', fk, bk,
          `Lookup ${fkCol} from ${fk} by ${bk}`, fk, 'No', UNKNOWN_KEY, 'Foreign Key', NA,
        ]);
        // Fact_Dim_Lookups: how the fact feed resolves the surrogate key.
        const current = dim?.scd_type === 'Type 2' ? ' (use current version)' : '';
        lookupRows.push([
          `${name}.${fkCol}`, bk, fk, bk, fkCol,
          `Match incoming ${bk} to ${fk}.${bk}${current}`, UNKNOWN_KEY,
          dim?.inferred ? 'Inferred dimension — confirm source' : dim?.scd_type === 'Type 2' ? 'Use current record' : 'Match on business key',
        ]);
        dqRows.push([nextDq(), name, fkCol, `Referential integrity to ${fk}`, 'High', 'Default to -1 (Unknown member)']);
      });

      // Column_Mapping — degenerate dimensions
      (fact.degenerate_dimensions ?? []).forEach((dd) =>
        colRows.push([mapId, name, clean(dd), inferType(dd), primarySrc, clean(dd), 'Direct copy', NA, 'Yes', NA, 'Degenerate Dimension', NA]),
      );

      // Column_Mapping — base measures
      (fact.base_measures ?? fact.measures ?? []).forEach((m) => {
        colRows.push([
          mapId, name, clean(m.name), clean(m.target_data_type) || 'DECIMAL(18,2)',
          clean(m.source_table) || primarySrc, clean(m.source_column),
          clean(m.transformation) || `${clean(m.aggregation)}(${clean(m.source_column)})`,
          NA, 'Yes', clean(m.default_value) || '0', 'Measure', clean(m.aggregation) || NA,
        ]);
        dqRows.push([nextDq(), name, clean(m.name), 'Must not be null and >= 0', 'Medium', 'Default to 0']);
      });

      // Column_Mapping — derived measures
      (fact.derived_measures ?? []).forEach((m) =>
        colRows.push([mapId, name, clean(m.name), 'DECIMAL(18,2)', NA, NA, clean(m.formula), NA, 'Yes', '0', 'Measure', 'Derived']),
      );

      // Column_Mapping — audit column
      colRows.push([mapId, name, 'dw_created_date', 'DATE', 'ETL System', NA, 'Load timestamp', NA, 'No', NA, 'Audit', NA]);

      // Visual_Flow
      flowRows.push([`${friendly(name)} Fact`, mappingSummary(name, srcList)]);
    });
  });

  // Guard rows when nothing matched the optional sheets
  if (joinRows.length === 1) joinRows.push([NA, NA, NA, NA, NA, 'No multi-table joins detected', NA, NA]);
  if (lookupRows.length === 1) lookupRows.push([NA, NA, NA, NA, NA, NA, UNKNOWN_KEY, 'No fact foreign keys detected']);

  /* ── SSIS lineage enrichment ──
     Insert "Original Source Table(s) (RAW)" next to every mart-layer source
     column, and add a Source_Lineage sheet documenting mart → original. */
  const lineageRows = [['Cognos/Mart Table', 'Original Source Table(s)', 'SSIS Package(s)', 'Status']];
  if (hasLineage) {
    // Source_To_Target_Map: after 'Source Tables' (index 3)
    mapRows.forEach((row, i) =>
      row.splice(4, 0, i === 0 ? 'Original Source Tables (RAW)' : origOfList(row[3])));
    // Column_Mapping: after 'Source Table' (index 4)
    colRows.forEach((row, i) =>
      row.splice(5, 0, i === 0 ? 'Original Source Table (RAW)' : origOf(row[4])));

    // Source_Lineage sheet — one row per mart table used by the reports.
    const seen = new Set();
    list.forEach((r) => {
      (r.result?.source_tables ?? []).forEach((t) => {
        const k = String(t).toLowerCase();
        if (!t || NOT_A_TABLE.test(String(t)) || seen.has(k)) return;
        seen.add(k);
        const hit = lookupOriginal(lineage, t);
        lineageRows.push([
          t,
          hit ? hit.sources.join(', ') : '',
          hit ? hit.packages.join(', ') : '',
          hit ? 'Mapped from SSIS' : '⚠ No SSIS package uploaded for this table',
        ]);
      });
    });
  }

  const wb = XLSX.utils.book_new();
  wb.Workbook = { Views: [{ RTL: false }] };

  const add = (rows, sheetName, widths) => {
    const ws = XLSX.utils.aoa_to_sheet(rows);
    if (widths) ws['!cols'] = widths.map((w) => ({ wch: w }));
    XLSX.utils.book_append_sheet(wb, ws, sheetName);
  };

  const readme = readmeRows(list);
  if (hasLineage) readme.splice(2, 0, readmeLineageRow(lineage));
  add(readme, 'README', [26, 92]);
  add(mapRows, 'Source_To_Target_Map',
    hasLineage ? [12, 12, 26, 40, 44, 40, 24, 60] : [12, 12, 26, 40, 40, 24, 60]);
  if (hasLineage) add(lineageRows, 'Source_Lineage', [36, 60, 36, 34]);
  add(joinRows, 'Source_Join_Rules', [12, 24, 26, 26, 12, 48, 32, 40]);
  add(colRows, 'Column_Mapping',
    hasLineage ? [12, 24, 26, 16, 26, 34, 26, 46, 22, 10, 14, 20, 16] : [12, 24, 26, 16, 26, 26, 46, 22, 10, 14, 20, 16]);
  add(lookupRows, 'Fact_Dim_Lookups', [28, 30, 24, 24, 24, 48, 16, 32]);
  add(etlRows(), 'ETL_Rules', [10, 18, 60, 22, 22]);
  add(dqRows, 'DQ_Rules', [12, 24, 24, 44, 10, 28]);
  add(flowRows, 'Visual_Flow', [30, 80]);

  return wb;
}

/* ── browser downloads ─────────────────────────────────── */
export async function exportExcel(results, lineage) {
  const { saveAs } = await import('file-saver');
  const wb = buildWorkbook(results, lineage);
  const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  saveAs(new Blob([wbout], { type: 'application/octet-stream' }), 'dimensional_model.xlsx');
}

export async function exportJSON(results) {
  const { saveAs } = await import('file-saver');
  const blob = new Blob([JSON.stringify(results, null, 2)], { type: 'application/json' });
  saveAs(blob, 'dimensional_model.json');
}
